[package]
org = "wso2"
name = "nballerina"
version = "0.1.0"
[build-options]
observabilityIncluded = false

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-platform-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/javacpp-1.5.9-SNAPSHOT-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.7-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-platform-15.0.7-1.5.9-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "target/platform-libs/llvm-15.0.7-1.5.9-SNAPSHOT-linux-x86_64.jar"
